# siteselection_config.yml

default:
 key1: default
 pkgs:
  - tidyverse
  - googledrive
  - ggplot2
  - ggpmisc
  - readxl
  - sf
  - topographer
  - terra
 extdata:  
   dem: '1sDKyVFypWFk0BbTe43PTuDv007XycZ23'
   siteindex: '1KPpaiTZSfrq0RYMJQwNdwgCU-4rWucheW5KUN_maERs'
   siteinfo21: 'EastRiver_Proposed_Sites_2021_25.csv'
   siteinfo22: 'EastRiver_Proposed_Sites_2022_10.csv'
   asp: '1C3QE-8xK2XGTE4TvGejMyu68D-QVvx85'
   aspcored: '1gxg1yOuD7qdMK5hKnk__vWobZ0zdsRz6'
 dat_raw: './data/raw'
 dat_int: './data/intermediate'
 dat_pro: './data/processed'

test:
  key1: test

production:
  key1: production

